// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkcmotWEf9Z0t9oE4TLuEba00xPdy_QA',
    appId: '1:355691089443:android:0f7291e234b968ed656b96',
    messagingSenderId: '355691089443',
    projectId: 'chattt-cc072',
    storageBucket: 'chattt-cc072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArbsiPcXJ-tM3-L-svMtD3I44gAGBx3zc',
    appId: '1:355691089443:ios:df13239a420b5800656b96',
    messagingSenderId: '355691089443',
    projectId: 'chattt-cc072',
    storageBucket: 'chattt-cc072.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzvwC6RFOvTq4XOFlIiqP0ujNNun58ZRI',
    appId: '1:355691089443:web:3abe752d911ed774656b96',
    messagingSenderId: '355691089443',
    projectId: 'chattt-cc072',
    authDomain: 'chattt-cc072.firebaseapp.com',
    storageBucket: 'chattt-cc072.firebasestorage.app',
    measurementId: 'G-VKHXPPMP7F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArbsiPcXJ-tM3-L-svMtD3I44gAGBx3zc',
    appId: '1:355691089443:ios:df13239a420b5800656b96',
    messagingSenderId: '355691089443',
    projectId: 'chattt-cc072',
    storageBucket: 'chattt-cc072.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzvwC6RFOvTq4XOFlIiqP0ujNNun58ZRI',
    appId: '1:355691089443:web:51c23b69f19f588d656b96',
    messagingSenderId: '355691089443',
    projectId: 'chattt-cc072',
    authDomain: 'chattt-cc072.firebaseapp.com',
    storageBucket: 'chattt-cc072.firebasestorage.app',
    measurementId: 'G-QDD8458614',
  );

}